#!/bin/bash
#
# A simple framework for regression testing the convert (ctest) script
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' 'input file name' 'expected output file name' 'expected std error file name'
#
# Some example test cases are given. You should add more test cases.
#
# CAUTION: Uses temporary files named test_err.txt and test_out.txt
# 
# Sam Scott, McMaster University, 2024
#
declare -i tc=0
declare -i fails=0

############################################
# Run a single test. Runs a given command 
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = input file name
#         $3 = expected std output file name
#         $4 = expected std error file name
#
# Assumes return value should be 0 if the
# std error file is empty. Otherwise it 
# should be 1.
#
# OUTPUTS: An pass/fail report showing the
# difference between expected and actual
# output on a failure (diff command)
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local INP=$2
    local EX_OUT=$3
    local EX_ERR=$4 

    EX_RET=1
    if [[ $(cat $EX_ERR) = "" ]]; then
        EX_RET=0
    fi
    $COMMAND < $INP > test_out.txt 2> test_err.txt
    RET=$?
    if [[ $RET != $EX_RET ]]; then
        echo "TC $tc Failed"
        echo "Returned $RET"
        echo "-----------"
        fails=$fails+1
        return
    fi
    DIFF=$(diff test_out.txt $EX_OUT)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed Standard Output"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi
    DIFF=$(diff test_err.txt $EX_ERR)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed Standard Error"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi

    echo "TC $tc Passed"
}

test './ctest' 'inp1.txt' 'ex_out1.txt' 'empty.txt'
test './ctest -b 2' 'inp2.txt' 'ex_out2.txt' 'empty.txt'
test './ctest -a' 'empty.txt' 'empty.txt' 'usage.txt'
# My added test cases:
test './ctest -b 10 -r -5 1' 'empty.txt' 'ex_out3.txt' 'empty.txt' #base case
test './ctest -b 100' 'empty.txt' 'empty.txt' 'usage.txt' #invalid base-input case (Boundary)
test './ctest -b 1' 'empty.txt' 'empty.txt' 'usage.txt' #invalid base-input case (Boundary)
test './ctest -b 36 -r' 'empty.txt' 'empty.txt' 'usage.txt' #invalid argument inputs case
test './ctest -b 2 -r 5 1' 'empty.txt' 'empty.txt' 'empty.txt' #invalid range case
test './ctest --help' 'empty.txt' 'help.txt' 'empty.txt' #--help flag case
test './ctest -b' 'empty.txt' 'empty.txt' 'usage.txt' #invalid base arguments case
test './ctest -b 2 -r 5 1' 'empty.txt' 'empty.txt' 'empty.txt' #invalid range case
test './ctest -b 36 -r 1 35' 'empty.txt' 'ex_out4.txt' 'empty.txt' #check if all chars (A-Z) work
test './ctest -b 10' 'inp3.txt' 'ex_out5.txt' 'nonlong.txt' #invalid - non long num input
test './ctest -b 10' 'inp4.txt' 'empty.txt' 'nonlong.txt' #invalid input; inputting words - non long num input
test './ctest -b 5' 'inp5.txt' 'ex_out6.txt' 'empty.txt' #user-input 0s
test './ctest' 'empty.txt' 'empty.txt' 'empty.txt' #entirely empty inputs
test './ctest -b 2 -r 0 0' 'empty.txt' 'ex_out7.txt' 'empty.txt' #same range values
test './ctest -b 2 -r 1 h' 'empty.txt' 'empty.txt' 'empty.txt' #string as range

# clean up
rm test_err.txt test_out.txt

# return code
exit $fails
