name: Pipeline for Testing convert.c

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build convert
      run: make convert
        
    - name: Upload convert
      uses: actions/upload-artifact@v4
      with:
        name: Convert Utility
        path: ./convert
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run/Build Tests
      run: make ctest; ./tests/test_script >test_results.txt; gcov ./ctest-main.c >coverage_report.txt
        
    - name: Upload Test Results
      if: ${{ always() }}

      uses: actions/upload-artifact@v4
      with:
        name: Ctest
        path: ./tests/test_results.txt

    - name: Upload Coverage Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Report
        path: ./tests/coverage_report.txt
