name: Pipeline for Testing convert.c

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc gcov

      - name: Build convert
        run: make convert

      - name: Upload convert
        uses: actions/upload-artifact@v4
        with:
          name: Convert Utility
          path: ./convert
  
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc gcov

      - name: Compile ctest with coverage
        run: make ctest

      - name: Run test script
        run: ./test_script > test_results.txt

      - name: Run gcov
        run: gcov ctest-main.c

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Ctest
          path: ./test_results.txt

    # Uncomment if you want to upload coverage reports
    # - name: Upload Coverage Report
    #   if: ${{ always() }}
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: Coverage Report
    #     path: ./coverage_report.txt
